### ISSUE TITLE
Crash the app when uploading

### ISSUE THREAD

**Issue by CyberRex0** [zamojski/TowerCollector#241]
When I pushed "Upload" button to upload collected cell data, Tower Collector was closed and returned to home screen.

My phone infomation:
- OS: Android 13 (API 33)
- Model: Sony Xperia 5 IV
- RAM: 8GB
- Tower Collector version: 2.15.2

recorded video of behavior:

https://github.com/user-attachments/assets/79faa13c-cf8e-49e6-a50a-394518bbf81d

<details>
<summary>
Crashlog:
</summary>

```
11-28 15:57:16.025 32296 32296 D AndroidRuntime: Shutting down VM
11-28 15:57:16.025 32296 32296 E AndroidRuntime: FATAL EXCEPTION: main
11-28 15:57:16.025 32296 32296 E AndroidRuntime: Process: info.zamojski.soft.towercollector, PID: 32296
11-28 15:57:16.025 32296 32296 E AndroidRuntime: android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{ca32928 32296:info.zamojski.soft.towercollector/u0a431} targetSDK=34 has been prohibited
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Parcel.readParcelable(Parcel.java:4852)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:3041)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:3024)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2966)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.app.Service.startForeground(Service.java:862)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at U0.d.a(SourceFile:4)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at U0.b.run(SourceFile:15)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:958)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8223)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-28 15:57:16.025 32296 32296 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
11-28 15:57:16.025  2097  2405 V WindowManager: Finish Transition #768: created at 11-28 15:57:15.775 collect-started=0.053ms request-sent=0.107ms started=13.972ms ready=71.414ms sent=84.851ms finished=249.432ms
11-28 15:57:16.026 32295 32295 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
11-28 15:57:16.026 32296 32296 E w       : CRASHED
11-28 15:57:16.026 32296 32296 E w       : android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{ca32928 32296:info.zamojski.soft.towercollector/u0a431} targetSDK=34 has been prohibited
11-28 15:57:16.026 32296 32296 E w       :      at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
11-28 15:57:16.026 32296 32296 E w       :      at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Parcel.readParcelable(Parcel.java:4852)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Parcel.createException(Parcel.java:3041)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Parcel.readException(Parcel.java:3024)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Parcel.readException(Parcel.java:2966)
11-28 15:57:16.026 32296 32296 E w       :      at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
11-28 15:57:16.026 32296 32296 E w       :      at android.app.Service.startForeground(Service.java:862)
11-28 15:57:16.026 32296 32296 E w       :      at U0.d.a(SourceFile:4)
11-28 15:57:16.026 32296 32296 E w       :      at U0.b.run(SourceFile:15)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Handler.handleCallback(Handler.java:958)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Looper.loopOnce(Looper.java:205)
11-28 15:57:16.026 32296 32296 E w       :      at android.os.Looper.loop(Looper.java:294)
11-28 15:57:16.026 32296 32296 E w       :      at android.app.ActivityThread.main(ActivityThread.java:8223)
11-28 15:57:16.026 32296 32296 E w       :      at java.lang.reflect.Method.invoke(Native Method)
11-28 15:57:16.026 32296 32296 E w       :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-28 15:57:16.026 32296 32296 E w       :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
11-28 15:57:16.026  2097  6671 W WindowManager: Exception thrown during dispatchAppVisibility Window{71153c8 u0 info.zamojski.soft.towercollector/info.zamojski.soft.towercollector.MainActivity EXITING}
11-28 15:57:16.026  2097  6671 W WindowManager: android.os.DeadObjectException
11-28 15:57:16.026  2097  6671 W WindowManager:         at android.os.BinderProxy.transactNative(Native Method)
11-28 15:57:16.026  2097  6671 W WindowManager:         at android.os.BinderProxy.transact(BinderProxy.java:584)
11-28 15:57:16.026  2097  6671 W WindowManager:         at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:562)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3285)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1227)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:414)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:7086)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5675)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5618)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.Transition.finishTransition(Transition.java:1196)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:875)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:397)
11-28 15:57:16.026  2097  6671 W WindowManager:         at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:286)
11-28 15:57:16.026  2097  6671 W WindowManager:         at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:182)
11-28 15:57:16.026  2097  6671 W WindowManager:         at android.os.Binder.execTransactInternal(Binder.java:1339)
11-28 15:57:16.026  2097  6671 W WindowManager:         at android.os.Binder.execTransact(Binder.java:1275)
11-28 15:57:16.026  2097  6671 I Process : Sending signal. PID: 32103 SIG: 9
11-28 15:57:16.027 32295 32295 I FirebaseInitProvider: FirebaseApp initialization successful
11-28 15:57:16.027 32296 32296 E a       : ACRA caught a InvalidForegroundServiceTypeException for info.zamojski.soft.towercollector
11-28 15:57:16.027 32296 32296 E a       : android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{ca32928 32296:info.zamojski.soft.towercollector/u0a431} targetSDK=34 has been prohibited
11-28 15:57:16.027 32296 32296 E a       :      at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
11-28 15:57:16.027 32296 32296 E a       :      at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Parcel.readParcelable(Parcel.java:4852)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Parcel.createException(Parcel.java:3041)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Parcel.readException(Parcel.java:3024)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Parcel.readException(Parcel.java:2966)
11-28 15:57:16.027 32296 32296 E a       :      at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
11-28 15:57:16.027 32296 32296 E a       :      at android.app.Service.startForeground(Service.java:862)
11-28 15:57:16.027 32296 32296 E a       :      at U0.d.a(SourceFile:4)
11-28 15:57:16.027 32296 32296 E a       :      at U0.b.run(SourceFile:15)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Handler.handleCallback(Handler.java:958)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Looper.loopOnce(Looper.java:205)
11-28 15:57:16.027 32296 32296 E a       :      at android.os.Looper.loop(Looper.java:294)
11-28 15:57:16.027 32296 32296 E a       :      at android.app.ActivityThread.main(ActivityThread.java:8223)
11-28 15:57:16.027 32296 32296 E a       :      at java.lang.reflect.Method.invoke(Native Method)
11-28 15:57:16.027 32296 32296 E a       :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-28 15:57:16.027 32296 32296 E a       :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
11-28 15:57:16.038 32296 32320 W .towercollector: ClassLoaderContext classpath element checksum mismatch. expected=215043585, found=3105438563 (DLC[];PCL[base.apk*215043585]{PCL[/system/framework/org.apache.http.legacy.jar*365604909]#PCL[/system/framework/com.android.media.remotedisplay.jar*2114713712]#PCL[/system/framework/com.android.location.provider.jar*3994156537]#PCL[/system/framework/org.apache.http.legacy.jar*365604909]} | DLC[];PCL[/data/app/~~8TluDOKTCXUAj6_z1-gmQA==/info.zamojski.soft.towercollector-kq8m16RqmB6pE4d5hFq3qQ==/base.apk*3105438563])
```
</details>

**Comment by secretmango** [comment]
Same here I guess

Set BeaconDB and OpencellID as backends. Now the app opens, tries to upload and immediately crashes, got unusable because of that.

**Comment by zamojski** [comment]
@CyberRex0 Thanks for the crashlog, I will take a look on this later today.

**Comment by zamojski** [comment]
It seems that `WorkManager` has the same issue, I was pretty sure all the errors I see in the reports come from `Collector` because they don't include anything valuable in stack trace, so once again thanks for reporting!

**Comment by secretmango** [comment]
The new update fixed it for me! It works again!

**Comment by anotherus3r** [comment]
> The new update fixed it for me! It works again!

Which app version are you on? I have  2.15.2 (no updates on Play Store when I check) but it still crashes.

**Comment by zamojski** [comment]
It's still being reviewed on Google Play, I cannot do anything about it...

**Comment by zamojski** [comment]
2.15.3 available in Google Play

**Comment by CyberRex0** [comment]
I confirmed it's fixed. thank you!
Also I donated you. Good luck :)

**Comment by zamojski** [comment]
Thanks! 🙂

**Comment by Swamp2k9** [comment]
It's fixed from my end as well. Will the F-Droid release get updated with this version?

**Comment by zamojski** [comment]
F-Droid version is build by F-Droid which I don't control. I will check if there's any issue with the build itself but it's very hard for me to event find the logs there...

**Comment by zamojski** [comment]
@licaon-kter maybe you know how to check latest build logs in F-Droid? I wasn't able to find it and F-Droid still shows the old version.

**Comment by Swamp2k9** [comment]
I see what you mean. I was using the F-Droid version when I started experiencing the crashes while uploading. 

I've just swapped to the GitHub version for fix. I'm using Obtanium to keep track of App updates.

**Comment by licaon-kter** [comment]
@zamojski https://f-droid.org/packages/info.zamojski.soft.towercollector/

Version 2.15.1 (2150112) -> [Download APK ](https://f-droid.org/repo/info.zamojski.soft.towercollector_2150112.apk)3.9 MiB [PGP Signature](https://f-droid.org/repo/info.zamojski.soft.towercollector_2150112.apk.asc) | [Build Log](https://f-droid.org/repo/info.zamojski.soft.towercollector_2150112.log.gz)

**Comment by zamojski** [comment]
@licaon-kter What about 2.15.2, 2.15.3 and 2.15.4? Were there any tries to build the app?

**Comment by licaon-kter** [comment]
2.15.3 was built in the current cycle and await publishing: https://monitor.f-droid.org/builds/log/info.zamojski.soft.towercollector/2150314#site-footer

(more info: https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client)

2.15.4 was just added and will we built in the next cycle: https://gitlab.com/fdroid/fdroiddata/-/commit/9893067ac59e81338ed7d8885052b4fad3448962

**Comment by zamojski** [comment]
Thanks a lot @licaon-kter !
