### ISSUE TITLE
App is stuck with initalizing GPS

### ISSUE THREAD

**Issue by jens1o** [zamojski/TowerCollector#76]
First of all, thanks for the project. I really like its idea, but so far I couldn't use it :(

When I hit the "Start recording" button (and wait for a while) nothing happens. I captured the debug output with logcat in Android Studio, however I'm not certain whether there is any personal-identifying content in there, so I would rather like to share it personally (via email)?

Still, for now I see the following errors logged:
```
2020-06-07 13:09:30.779 21537-15496/? E/SQLiteDatabase: Error inserting flex_time=2731000 job_id=-1 period=5464000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=201817000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1591528170769 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
        at apiz.a(:com.google.android.gms@201817039@20.18.17 (120408-311416286):78)
        at apio.a(:com.google.android.gms@201817039@20.18.17 (120408-311416286):196)
        at apio.a(:com.google.android.gms@201817039@20.18.17 (120408-311416286):20)
        at apio.a(:com.google.android.gms@201817039@20.18.17 (120408-311416286):190)
        at apex.run(:com.google.android.gms@201817039@20.18.17 (120408-311416286):8)
        at sfd.b(:com.google.android.gms@201817039@20.18.17 (120408-311416286):12)
        at sfd.run(:com.google.android.gms@201817039@20.18.17 (120408-311416286):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sld.run(:com.google.android.gms@201817039@20.18.17 (120408-311416286):0)
        at java.lang.Thread.run(Thread.java:919)
2020-06-07 13:09:30.794 21537-14674/? E/SQLiteDatabase: Error inserting flex_time=2731000 job_id=-1 period=5464000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=201817000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1591528170788 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
        at apiz.a(:com.google.android.gms@201817039@20.18.17 (120408-311416286):78)
        at apio.a(:com.google.android.gms@201817039@20.18.17 (120408-311416286):196)
        at apio.a(:com.google.android.gms@201817039@20.18.17 (120408-311416286):20)
        at apio.a(:com.google.android.gms@201817039@20.18.17 (120408-311416286):190)
        at apex.run(:com.google.android.gms@201817039@20.18.17 (120408-311416286):8)
        at sfd.b(:com.google.android.gms@201817039@20.18.17 (120408-311416286):12)
        at sfd.run(:com.google.android.gms@201817039@20.18.17 (120408-311416286):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at sld.run(:com.google.android.gms@201817039@20.18.17 (120408-311416286):0)
        at java.lang.Thread.run(Thread.java:919)
```

I use the *motorola one vision* (it's a dual sim phone but I only use one slot).

These SQLite errors seem interesting, however I'm not certain whether that is intended behavior.

**Comment by zamojski** [comment]
The log is not useful, I think this is an some internal problem of Google Analytics library but not Tower Collector itself. Please follow the steps described in [FAQ](https://zamojski.info/FAQ,Tower-Collector.html#EnableDiagnosticLogging) and send me the log file by email (contact link on the same page). The log will contain sensitive data like cell tower to which the phone is connected and GPS locations.

**Comment by jens1o** [comment]
Thanks for your reply and help. I just sent the e-mail with the log to you.

**Comment by jens1o** [comment]
Thanks to @zamojski, this is resolved. I just needed to wait a little bit longer (going outside with clearance to the sky also made it a lot faster process).
